config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  namespace :users do
    resources :contributions, only: [:index]
    resources :locations, only: [:index]
  end
  resources :locations do
    resources :comments, only: [:index, :create] # check where goes the comments
    resources :contributions, only: [:new, :create]
    resources :checkins, only: [:create]
  end
  resources :contributions, only: [:edit, :update, :destroy]
  resources :news, only: [:index]
  resources :checkins, only: [:destroy]
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user, optional: true
  has_many :contributions, dependent: :destroy
  accepts_nested_attributes_for :contributions
  has_many :comments, dependent: :destroy
  has_many :checkins, dependent: :destroy

  validates :name, presence: true

  enum location_type: {
    individual: 0,
    ngo: 1,
    shelter: 2
  }, _default: 0

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: %i[address name],
                  associated_against: {
                    contributions: %i[supply_type]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :comments, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :locations, through: :contributions
  has_one :checkin, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @coords = request.location
    @locations = policy_scope(Location).eager_load([:contributions, :checkins])
    @locations = @locations.where(location_type: params[:location_type]) if params[:location_type]
    @locations = @locations.near([35.633868, 139.708205], 0.8)
    params[:search].present? && @locations = Location.global_search(params[:search]["search"])
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        id: location.id,
        info_window: render_to_string(partial: "info_window", locals: { location: location }),
        image_url: helpers.asset_url(marker_icon(location.location_type))
      }
    end
    @user_asset = {
      image_url: helpers.asset_url('user.png')
    }
    # @locations = request.location

  end

  def show
    @location = Location.find(params[:id])
    authorize @location
    @location_contributions = Contribution.where(location_id: @location.id) # current location show...?
    @comment = Comment.new
    @comments = Comment.where(location_id: @location.id)
    @marker_location = Location.where(id: params[:id])
    @markers = @marker_location.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        id: location.id,
        image_url: helpers.asset_url(marker_icon(location.location_type))
      }
    end
    @checkin = Checkin.find_by(user: current_user, location: @location) || Checkin.new
    @user_asset = {
      image_url: helpers.asset_url('user.png')
    }
  end

  def new
    @location = Location.new
    authorize @location
    @location.contributions.build
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.contributions.first.user = current_user
    authorize @location
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize @location
  end

  def update
    @location = Location.find(params[:id])
    authorize @location
    @location.update(location_params)
    redirect_to location_path(@location)
  end

  def destroy
    @location = Location.find(params[:id])
    authorize @location
    @location.destroy
    redirect_to locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :location_type, contributions_attributes: {})
  end

  def marker_icon(location)
    case location
    when "individual"
      return 'contribution_location.png'
    when "ngo"
      return 'ngo.png'
    when "shelter"
      return 'shelter.png'
    else
      return 'location-sign.png'
    end
  end

  def filter_location
    if request.location.latitude.present?
      [request.location.latitude, request.location.longitude]
    else
      [35.633868, 139.708205]
    end
  end
end

app/controllers/users/contributions_controller.rb
class Users::ContributionsController < ApplicationController
  def index
    @contributions = policy_scope([:user, Contribution]).order(created_at: :desc)
  end
end

app/controllers/users/locations_controller.rb
class Users::LocationsController < ApplicationController
  def index
    @locations = policy_scope([:user, Location]).order(created_at: :desc)
  end
end

app/views/users/locations/_location_card.html.erb
<div class="contri-user mt-4 p-2 mb-2">
  <div class="border-bottom mt-3 mb-3">
    <small><%= location.location_type %></small>
    <h2><%= location.name %></h2>
    <small class="text-success">Your Contribution</small>
    <% location.contributions.each do |contribution| %>
      <div class="contri-card-mint p-1">
        <small class="text-uppercase"><strong><%= contribution.supply_type %>, </strong></small>
        <small class="text-uppercase"><strong><%= contribution.quantity ? contribution.quantity : 'Unknown' %></strong></small>
        <p><%= contribution.description%></p>
      </div>
    </div>
    <div class="d-flex ">
      <%= link_to edit_contribution_path(contribution), class: "text-decoration-none" do%>
        <p><i class="fas fa-edit"></i> Edit</p>
      <%end%>
      &nbsp
      &nbsp
      <%= link_to new_location_contribution_path([location, contribution]), class: "text-decoration-none" do%>
        <p><i class="fas fa-edit"></i> Add </p>
      <%end%>
      &nbsp
      &nbsp
      <%= link_to contribution_path(contribution),
    method: :delete,
    data: { confirm: "Do you want to delete this contribution?"},
    class: "text-decoration-none text-danger" do%>
        <p><i class="fas fa-times"></i> Delete</p>
      <%end%>
    </div>
  <% end %>
</div>

app/views/users/locations/index.html.erb
<div class="container">
  <h1 class="text-success">My Locations</h1>
  <% @locations.each do |location| %>
    <%= render "users/locations/location_card", location: location %>
  <% end %>
</div>