config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  namespace :users do
    resources :contributions, only: [:index]
    resources :locations, only: [:index]
  end
  resources :locations do
    resources :comments, only: [:index, :create] # check where goes the comments
    resources :contributions, only: [:new, :create]
    resources :checkins, only: [:create]
  end
  resources :contributions, only: [:edit, :update, :destroy]
  resources :news, only: [:index]
  resources :checkins, only: [:destroy]
end

app/views/shared/_bottom_navbar.erb
<div class="user-nav-bar d-flex justify-content-around align-items-center">
  <div class= "icon-color" data-bs-toggle="modal" data-bs-target="#emergencyModal">
    <%= image_tag "white_icon/emergency_call_01.png" %>
  </div>
  <div class= "icon-color">
    <%= link_to(locations_path(:location_type => 'ngo')) do %>
      <%= image_tag "white_icon/ngo-white.png" %>
    <% end %>
  </div>
  <div class= "icon-color">
    <%= link_to(locations_path(:location_type => 'shelter')) do %>
      <%= image_tag "white_icon/shelter.png" %>
    <% end %>
  </div>
  <!-- NEW HERE -->
  <% if user_signed_in? %>
    <li class="nav-item dropdown icon-color">
      <%= image_tag ("white_icon/profile.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Add a Location", new_location_path, class: "dropdown-item" %>
        <%= link_to "My locations", users_locations_path, class: "dropdown-item" %>
        <%= link_to "My contributions", users_contributions_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
  <% else %>
    <div class= "icon-color">
      <%= link_to new_user_session_path do %>
        <%= image_tag "white_icon/profile.png" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal.html.erb
<div>
  <div class="modal fade" id="emergencyModal" tabindex="-1" role="dialog" aria-labelledby="emergencyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="emergencyModalLabel">Emergency Numbers</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body text-center">
          <a href="tel:110">110</a>
          <p>Police</p>
          <a href="tel:119">119</a>
          <p>Fire, Ambulance, Rescue</p>
          <a href="tel:03-3503-8484">03-3503-8484</a>
          <p>Police Consultation(English)</p>
          <a href="tel:171">171</a>
          <p>Disaster Voice Message</p>
          <a href="tel:0120-805-261">0120-805-261</a>
          <p>Tokyo Multilingual Call Center</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-flat" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag asset_path('icon-brand.png') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active ">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_shared.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'traq_logo.png'%>
    <% end %>
  </div>
</div>