config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  namespace :users do
    resources :contributions, only: [:index]
    resources :locations, only: [:index]
  end
  resources :locations do
    resources :comments, only: [:index, :create] # check where goes the comments
    resources :contributions, only: [:new, :create]
    resources :checkins, only: [:create]
  end
  resources :contributions, only: [:edit, :update, :destroy]
  resources :news, only: [:index]
  resources :checkins, only: [:destroy]
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user, optional: true
  has_many :contributions, dependent: :destroy
  accepts_nested_attributes_for :contributions
  has_many :comments, dependent: :destroy
  has_many :checkins, dependent: :destroy

  validates :name, presence: true

  enum location_type: {
    individual: 0,
    ngo: 1,
    shelter: 2
  }, _default: 0

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: %i[address name],
                  associated_against: {
                    contributions: %i[supply_type]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @coords = request.location
    @locations = policy_scope(Location).eager_load([:contributions, :checkins])
    @locations = @locations.where(location_type: params[:location_type]) if params[:location_type]
    @locations = @locations.near([35.633868, 139.708205], 0.8)
    params[:search].present? && @locations = Location.global_search(params[:search]["search"])
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        id: location.id,
        info_window: render_to_string(partial: "info_window", locals: { location: location }),
        image_url: helpers.asset_url(marker_icon(location.location_type))
      }
    end
    @user_asset = {
      image_url: helpers.asset_url('user.png')
    }
    # @locations = request.location

  end

  def show
    @location = Location.find(params[:id])
    authorize @location
    @location_contributions = Contribution.where(location_id: @location.id) # current location show...?
    @comment = Comment.new
    @comments = Comment.where(location_id: @location.id)
    @marker_location = Location.where(id: params[:id])
    @markers = @marker_location.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        id: location.id,
        image_url: helpers.asset_url(marker_icon(location.location_type))
      }
    end
    @checkin = Checkin.find_by(user: current_user, location: @location) || Checkin.new
    @user_asset = {
      image_url: helpers.asset_url('user.png')
    }
  end

  def new
    @location = Location.new
    authorize @location
    @location.contributions.build
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.contributions.first.user = current_user
    authorize @location
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize @location
  end

  def update
    @location = Location.find(params[:id])
    authorize @location
    @location.update(location_params)
    redirect_to location_path(@location)
  end

  def destroy
    @location = Location.find(params[:id])
    authorize @location
    @location.destroy
    redirect_to locations_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :location_type, contributions_attributes: {})
  end

  def marker_icon(location)
    case location
    when "individual"
      return 'contribution_location.png'
    when "ngo"
      return 'ngo.png'
    when "shelter"
      return 'shelter.png'
    else
      return 'location-sign.png'
    end
  end

  def filter_location
    if request.location.latitude.present?
      [request.location.latitude, request.location.longitude]
    else
      [35.633868, 139.708205]
    end
  end
end

app/controllers/users/locations_controller.rb
class Users::LocationsController < ApplicationController
  def index
    @locations = policy_scope([:user, Location]).order(created_at: :desc)
  end
end

app/views/locations/_card.html.erb
<div data-mapbox-target="location" data-location-id="<%= location.id %>" class="card-blue-shadow mb-4 p-4">
  <small><%= location.location_type%></small>
  <%= render "locations/location_kind", location: location %>
  <h2><%= location.name %></h2>
  <% if location.tel.present? %>
    <small><i class="fas fa-phone-alt"></i> - <strong><%= location.tel %></strong></small>
  <% end %>
  <br>
  <% if location.contributions.present?%>
    <small class="text-success">Supplies Available</small>
    <% location.contributions.each do |contribution| %>
      <div class="contri-card-mint p-2 mt-2">
        <%= render "locations/supplies_kind", contribution: contribution %>
      </div>
      <p class="distance"></p>
    <%end%>
  <%else%>
    <div class="contri-card-grey p-1">
      <small class="text-muted">No Supplies Available</small>
    </div>
    <p class="distance"></p>
  <% end %>
  <% if location.location_type == "shelter" %>
    <p class="card-user-count"><i class="fas fa-male"></i> <%= location.checkins.count %></p>
  <% end %>
  <div class="d-flex justify-content-center">
    <%= link_to 'Get Direction', location_path(location), class:"btn btn-flat mt-2"%>
  </div>
</div>

app/views/locations/_checkin_btn.html.erb
<% if @checkin.new_record? %>
  <%= simple_form_for([@location, @checkin], remote: true) do |f| %>
    <%= f.submit 'Check in', class:"btn btn-flat ps-4 pe-4 ms-3" %>
  <% end %>
<% else %>
  <%= link_to 'Check out', checkin_path(@checkin),
          class: "btn btn-flat ps-4 pe-4 ms-3",
          method: :delete,
          remote: true %>
<% end %>

app/views/locations/_checkin_modal.html.erb
<div>
<div class="modal fade" id="btncheckin" tabindex="-1" role="dialog" aria-labelledby="checkinModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="checkinModalLabel">Success</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
  <span><strong>Great!</strong> we are happy to have you here!</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>

app/views/locations/_info_window.html.erb
<div class="container">
  <h2><%= location.location_type %></h2>
  <p><%= location.address %></p>
  <% if location.location_type == "shelter" %>
    <small class="card-user-count" data-checkin-target="count"><i class="fas fa-male"></i> - <%= location.checkins.count %></small>
  <% end %>
  <ul>
    <% location.contributions.each do |contribution| %>
      <li><%= contribution.supply_type %></li>
    <% end %>
  </ul>
  <br>
  <%= link_to "info", location_path(location) %>
</div>

app/views/locations/_location_kind.html.erb
<%if location.location_type == 'shelter'%>
    <p class="text-success"><i class="fas fa-shower">&nbsp</i><i class="fas fa-bed"></i>&nbsp<i class="fas fa-band-aid"></i></p>
  <%else%>
  <%end%>

app/views/locations/_supplies_kind.html.erb
<small class="text-success text-uppercase"><i class="fas <%= Contribution::SUPPLY_ICON[contribution.supply_type]%>"><small class="text-success text-uppercase"><%= contribution.supply_type %></i></small></small>

app/views/locations/edit.html.erb
<div class="container">
  <h1>Edit#location</h1>
  <%= simple_form_for(@location) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :location_type, collection: ['Contributor', 'NGO'] %>
    <%= f.submit %>
  <% end %>
</div>

app/views/locations/index.html.erb
<div class="container px-4"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-userPosition-value="<%= @user.to_json %>"
  <%# Are we using line 4? %>
  data-mapbox-user-asset-value="<%= @user_asset.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div style="width: 100%; height: 400px; border-radius: 8px; box-shadow: 2px 2px 10px #d0e1ff;"
  data-mapbox-target="map">
  </div>
  <%#= link_to 'Add location', new_location_path %>
  <div class="locations_card mt-4 testWrapper">
    <% @locations.each do |location| %>
      <%= render "locations/card", location: location %>
    <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-4 p-4">
    <div class="card-no-hover p-4">
      <h1 class="card-text-title text-primary text-center">New Location</h1>
      <p>Please register a new location in order to distribute supplies.
        You may add or edit the information later in the edit page.</p>
      <%= simple_form_for @location do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :tel %>
        <%= f.input :location_type, collection: ['ngo'], include_blank: false %>
        <%= f.simple_fields_for :contributions do |g| %>
          <%= g.input :supply_type, collection: ["Water", "Food", "Medicine", "Sanitation", "Others"],input_html: {class:"comment-box"}, include_blank: false %>
          <%#= g.input :supply_type, input_html: {class:"comment-box"} %>
          <%= g.input :description, input_html: {class:"comment-box"} %>
          <%= g.input :quantity, input_html: {class:"comment-box"} %>
        <% end %>
        <%= f.button :submit, "Add Contribution", class:"btn btn-flat" %>
      <% end %>
      <%#= link_to 'Check Contributions', location_path(@location), class:"btn btn-outline mt-2" %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="container mt-4 px-4 mb-4"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-user-asset-value="<%= @user_asset.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-mapbox-user-id-value="<%= current_user&.id %>"
  data-mapbox-location-user-id-value="<%= @location.user_id.present? ? @location.user_id : 00000000 %>">
  <div class="card-no-hover p-4 mb-4"
  data-mapbox-target="location"
  data-location-id="<%= @location.id %>">
    <h1 class="text-shelter"><%= @location.location_type %></h1>
    <%= render "locations/location_kind", location: @location %>
    <h1 class="card-text-title text-primary"><%= @location.name %></h1>
    <p><%= @location.address%></p>
    <% if @location.tel.present? %>
      <small><i class="fas fa-phone-alt"></i> - <strong><%= @location.tel %></strong></small>
    <% end %>
    <% if @location.contributions.present?%>
      <p class="mint-green-text">SUPPLIES AVAILABLE</p>
      <% @location_contributions.each do |contribution| %>
        <div class="contri-card-mint mt-2 p-2">
          <div class="d-flex flex-row">
            <small><strong><%= contribution.quantity ? contribution.quantity : 'Unknown' %></strong></small>
            &nbsp
            <small><strong><%= contribution.supply_type %></strong></small>
          </div>
          <p><%= contribution.description %></p>
        </div>
      <% end %>
    <%else%>
      <div class="contri-card-grey p-1">
        <small class="text-muted">NO SUPPLIES AVAILABLE</small>
      </div>
    <% end %>
    <div class="d-flex justify-content-center mt-2" data-controller="checkin">
      <% if user_signed_in? %>
        <% if @location.user_id != current_user.id %>
          <a class="btn btn-flat" href="#map-anchor" remote="true">See Route</a>
        <% end %>
        <% if @location.location_type == "shelter"%>
          <%= render "locations/checkin_btn", location: @location %>
          <%= render 'checkin_modal' %>
        <% end %>
      <% end %>
    </div>
    <div class="card-no-hover mt-4 p-4 mb-4">
      <div class="comments">
        <div class="messages">
          <% @comments.each do |comment| %>
            <p id="Notice-<%= comment.id %>"><i class="fas fa-angle-right"></i> <%= comment.content %></p>
            <small><%= comment.created_at.strftime("%m-%d-%Y %I:%M%p") %></small>
          <% end %>
        </div>
        <div>
          <% if user_signed_in? %>
            <% if @location.user_id == current_user.id %>
              <%= simple_form_for([@location, @comment], remote: true) do |f| %>
                <%= f.input :content, input_html: {class:"comment-box"}  %>
                <div class="text-center">
                  <%= f.button :submit, "Add Notice", class:"btn btn-flat" %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% if user_signed_in? && @location.user == current_user %>
      <%= link_to edit_location_path(@location), class: "text-decoration-none"  do %>
        <i class="fas fa-edit"></i>
      <% end %>
    <% end %>
    <p class="distance"></p>
    <% if @location.location_type == "shelter" %>
      <p class="card-user-count" data-checkin-target="count"><i class="fas fa-male"></i> <%= @location.checkins.count %></p>
    <% end %>
  </div>
  <div id="map-anchor" style="width: 100%; height: 500px; border-radius: 8px; box-shadow: 2px 2px 10px #d0e1ff;"
    data-mapbox-target="map">
  </div>
</div>